name: dyne
dependencies:
- alabaster=0.7.7=py27_0
- appnope=0.1.0=py27_0
- babel=2.2.0=py27_0
- cycler=0.10.0=py27_0
- decorator=4.0.9=py27_0
- docutils=0.12=py27_0
- freetype=2.5.5=0
- h5py=2.5.0=np110py27_4
- hdf5=1.8.15.1=2
- ipython=4.1.2=py27_0
- ipython_genutils=0.1.0=py27_0
- jinja2=2.8=py27_0
- libpng=1.6.17=0
- markupsafe=0.23=py27_0
- matplotlib=1.5.1=np110py27_0
- mkl=11.3.1=0
- numpy=1.10.4=py27_0
- openssl=1.0.2g=0
- pandas=0.17.1=np110py27_0
- path.py=8.1.2=py27_1
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pip=8.1.0=py27_0
- pygments=2.1.1=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_1
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- python.app=1.2=py27_4
- pytz=2015.7=py27_0
- qt=4.8.7=1
- readline=6.2=2
- scipy=0.17.0=np110py27_0
- setuptools=20.2.2=py27_0
- simplegeneric=0.8.1=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- snowballstemmer=1.2.1=py27_0
- sphinx=1.3.5=py27_0
- sphinx_rtd_theme=0.1.9=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- traitlets=4.1.0=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.8=0
- pip:
  - ipython-genutils==0.1.0
  - mtspec (/Users/akhambhati/Developer/compiles/mtspec)==0.3.x
  - sphinx-rtd-theme==0.1.9

